# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/s1231893/DigiLab/IR_Transmitter/IR_Transmitter.cache/wt [current_project]
set_property parent.project_path /home/s1231893/DigiLab/IR_Transmitter/IR_Transmitter.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  /home/s1231893/DigiLab/IR_Transmitter/IR_Transmitter.srcs/sources_1/new/NewCounter.v
  /home/s1231893/DigiLab/IR_Transmitter/IR_Transmitter.srcs/sources_1/imports/Snake/Seg7Decoder.v
  /home/s1231893/DigiLab/IR_Transmitter/IR_Transmitter.srcs/sources_1/new/IRTransmitterSM.v
  /home/s1231893/DigiLab/IR_Transmitter/IR_Transmitter.srcs/sources_1/new/IRTransmitterMaster.v
  /home/s1231893/DigiLab/IR_Transmitter/IR_Transmitter.srcs/sources_1/imports/proc/ALU.v
  /home/s1231893/DigiLab/IR_Transmitter/IR_Transmitter.srcs/sources_1/new/IR_Processor_Interface.v
  /home/s1231893/DigiLab/IR_Transmitter/IR_Transmitter.srcs/sources_1/imports/proc/Timer.v
  /home/s1231893/DigiLab/IR_Transmitter/IR_Transmitter.srcs/sources_1/imports/proc/ROM.v
  /home/s1231893/DigiLab/IR_Transmitter/IR_Transmitter.srcs/sources_1/imports/proc/RAM.v
  /home/s1231893/DigiLab/IR_Transmitter/IR_Transmitter.srcs/sources_1/imports/proc/Processor.v
  /home/s1231893/DigiLab/IR_Transmitter/IR_Transmitter.srcs/sources_1/new/Processor_Wrapper.v
}
read_xdc /home/s1231893/DigiLab/IR_Transmitter/IR_Transmitter.srcs/constrs_1/new/IRTransmitterMaster_constraints.xdc
set_property used_in_implementation false [get_files /home/s1231893/DigiLab/IR_Transmitter/IR_Transmitter.srcs/constrs_1/new/IRTransmitterMaster_constraints.xdc]

synth_design -top Processor_Wrapper -part xc7a35tcpg236-1
write_checkpoint -noxdef Processor_Wrapper.dcp
catch { report_utilization -file Processor_Wrapper_utilization_synth.rpt -pb Processor_Wrapper_utilization_synth.pb }
